ALTER TABLE Table1 
ADD CreatedDate DATETIME DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE Table1 
ADD ModifiedDate DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE Table1 
ADD ModifiedBy VARCHAR(50);
